---
  name: J2 Lint
  
  on:
    pull_request_target:
      branches:
        - equuleus
        - sagitta
  
  permissions:
    pull-requests: write
    contents: read
  
  jobs:
    j2lint:
      uses: vyos/.github/.github/workflows/lint-j2.yml@current
      secrets: inherit